version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: etrade_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - etrade-net

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - etrade-net

networks:
  etrade-net:
